services:
  - type: web
    name: newpot-backend
    runtime: node
    plan: free
    rootDir: newpot-hbny-be-main
    buildCommand: npm install --include=dev && npx prisma migrate deploy --config prisma/prisma.config.ts && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://newpot-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false

  - type: web
    name: newpot-frontend
    runtime: node
    plan: free
    rootDir: newpot-hbny-main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://newpot-backend.onrender.com/api

  - type: web
    name: admin-frontend
    runtime: node
    plan: free
    rootDir: admin-main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://newpot-backend.onrender.com
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://admin-frontend-wtsq.onrender.com
      - key: AUTH_URL
        value: https://admin-frontend-wtsq.onrender.com
      - key: APPROVED_ACCOUNT_URL
        value: https://newpot-frontend.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
